---

- title: Reviewer 
  affiliation: Journal of Network and Computer Applications (JNCA) 
  date: 2020-2022

- title: Reviewer 
  affiliation: Computers & Security
  date: 2021-2022

- title: Reviewer 
  affiliation: ETRI Journal
  date: 2017-2022

- title: Reviewer 
  affiliation: International Journal of Communication Systems
  date: 2021

- title: Reviewer 
  affiliation: IEEE Access
  date: 2019-2020

- title: Reviewer 
  affiliation: IEEE/CAA Journal of Automatica Sinica (JAS) 
  date: 2020

- title: Artifact Committee 
  affiliation: Annual Computer Security Applications Conference (ACSAC) 2019 
  date: 2019
