---
- title: (대학ICT연구센터(ITRC)) 초광역 연합의료 AI연구센터
  order: 과학기술정보통신부
  date: 2024.07. - 2032.12.

- title: (보안)
  order: 국가보안연구소
  date: 2024.06. - 2024.11.  

- title: (창의도전연구) 다중-최적 진화강화학습 기반 인간친화 엔터테인먼트 인공지능
  order: 한국연구재단(교육부)
  date: 2023.06. - 2026.05.

- title: (우수신진연구-최초혁신실험실) 신뢰할 수 있는 URLLC 네트워킹을 위한 하드웨어 기반 MEC 네트워크 시스템의 설계
  order: 한국연구재단(NRF)
  date: 2022.07. - 2022.12.

- title: 사물인터넷 보안을 위한 네트워크 플랫폼
  order: 전남대학교
  date: 2022.05. - 2022.12.

- title: 서버-엣지 협업 기반 저지연 AI 컴퓨팅 및 하드웨어 보안 기술 연구
  order: 한국전자통신연구원(ETRI)
  date: 2022.03. - 2022.10.

- title: (우수신진연구) 신뢰할 수 있는 URLLC 네트워킹을 위한 하드웨어 기반 MEC 네트워크 시스템의 설계
  order: 한국연구재단(NRF)
  date: 2022.03. - 2026.02.

- title: 차세대통신 혁신융합 사업단
  order: 과학기술정보통신부
  date: 2023.06 - 2028.12

- title: 정보보호 특성화 대학
  order: 한국인터넷진흥원(KISA)
  date: 2023.06 - 2028.12

- title: 인공지능융합혁신인재양성사업단(AI융합혁신대학원)
  order: 과학기술정보통신부
  date: 2023.07 - 2026.12.

- title: 융합보안대학원
  order: 정보통신기획평가원(IITP)
  date: 2022.01 - 2024.12

- title: 인공지능혁신공유대학사업단
  order: 교육부
  date: 2021.05 - 2027.02.

- title: 소프트웨어중심대학사업단
  order: 과학기술정보통신부
  date: 2021.04 - 2028.12.

- title: (BK21 4단계) 인공지능융합인재양성사업단
  order: 교육부
  date: 2020.09 - 2027.08.  

- title: 광주전남지역혁신플랫폼
  order: 교육부
  date: 2020.06 - 2024.05.
